# Generated by Django 6.0.5 on 2026-05-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetlabLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the user.', max_length=150)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('GUEST', 'Guest')], default='STUDENT', max_length=20)),
                ('id_number', models.CharField(blank=True, help_text='Required for Students. Leave blank for Guests.', max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Netlab Log',
                'verbose_name_plural': 'Netlab Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
