# Generated by Django 6.0.5 on 2026-05-13 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netlablog',
            name='id_number',
            field=models.CharField(blank=True, help_text='Required for Students (Numbers only). Leave blank for Guests.', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='ID Number must contain only numbers.', regex='^\\d+$')]),
        ),
    ]
