# Generated by Django 6.0.5 on 2026-05-13 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_alter_netlablog_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netlablog',
            name='id_number',
            field=models.CharField(blank=True, help_text='Required for Students (Numbers only). Leave blank for Guests.', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='ID Number must contain only numbers and be up to 10 digits long.', regex='^\\d{1,10}$')]),
        ),
    ]
