# Generated by Django 6.0.5 on 2026-05-14 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_alter_netlablog_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netlablog',
            name='id_number',
            field=models.CharField(blank=True, help_text='Required for Students (Numbers only). Leave blank for Guests.', max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='ID Number must contain only numbers and be up to 8 digits long.', regex='^\\d{8}$')]),
        ),
    ]
