# Generated by Django 6.0.5 on 2026-05-14 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0006_alter_netlablog_id_number_alter_netlablog_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netlablog',
            name='name',
            field=models.CharField(help_text='Full name of the user.', max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only letters and spaces are allowed.')]),
        ),
    ]
