# Generated by Django 6.0.5 on 2026-05-15 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0007_alter_netlablog_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(help_text='The official Learner ID Number.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='ID Number must contain only numbers and be up to 8 digits long.', regex='^\\d{8}$')])),
                ('full_name', models.CharField(help_text='The official Full Name of the Learner.', max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only letters and spaces are allowed.')])),
            ],
            options={
                'verbose_name': 'Learner Profile',
                'verbose_name_plural': 'Learner Profiles',
                'ordering': ['id_number'],
            },
        ),
    ]
