# Generated by Django 6.0.5 on 2026-05-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0008_learnerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='department',
            field=models.CharField(choices=[('CCS', 'CCS'), ('CASED', 'CASED'), ('CBA', 'CBA')], default='CCS', help_text='The department of the Learner.', max_length=5),
        ),
    ]
