# Generated by Django 6.0.5 on 2026-05-19 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0009_learnerprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='id_number',
            field=models.CharField(help_text='The official Learner ID Number.', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='ID Number must contain only numbers and be up to 8 digits long.', regex='^\\d{8}$')]),
        ),
    ]
