# Generated by Django 6.0.5 on 2026-05-20 02:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0010_alter_learnerprofile_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='netlablog',
            name='department',
            field=models.CharField(blank=True, choices=[('CCS', 'College of Computer Studies'), ('CBA', 'College of Business and Administration'), ('COE', 'College of Engineering'), ('CASED', 'College of Arts, Science, and Education'), ('CON', 'College of Nursing'), ('COA', 'College of Architecture')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='netlablog',
            name='logged_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='department',
            field=models.CharField(choices=[('CCS', 'College of Computer Studies'), ('CBA', 'College of Business and Administration'), ('COE', 'College of Engineering'), ('CASED', 'College of Arts, Science, and Education'), ('CON', 'College of Nursing'), ('COA', 'College of Architecture')], default='CCS', max_length=10),
        ),
    ]
