# Generated by Django 6.0.5 on 2026-05-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0010_alter_learnerprofile_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='netlablog',
            name='purpose',
            field=models.CharField(blank=True, help_text='The purpose of the visit (e.g., Internet, Print).', max_length=50, null=True),
        ),
    ]
