# Generated by Django 6.0.5 on 2026-05-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0011_netlablog_department_netlablog_logged_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='department',
            field=models.CharField(choices=[('CCS', 'Ccs'), ('CBA', 'Cba'), ('COE', 'Coe'), ('CASED', 'Cased'), ('CON', 'Con'), ('COA', 'Coa')], default='CCS', max_length=10),
        ),
        migrations.AlterField(
            model_name='netlablog',
            name='department',
            field=models.CharField(blank=True, choices=[('CCS', 'Ccs'), ('CBA', 'Cba'), ('COE', 'Coe'), ('CASED', 'Cased'), ('CON', 'Con'), ('COA', 'Coa')], max_length=10, null=True),
        ),
    ]
