# Generated by Django 6.0.5 on 2026-05-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0011_netlablog_purpose'),
        ('logger', '0012_alter_learnerprofile_department_and_more'),
    ]

    operations = [
    ]
