# Generated by Django 6.0.5 on 2026-05-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0013_merge_20260520_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('CCS', 'Ccs'), ('CBA', 'Cba'), ('COE', 'Coe'), ('CASED', 'Cased'), ('CON', 'Con'), ('COA', 'Coa')], default=None, max_length=10, null=True),
        ),
    ]
