# Generated by Django 6.0.5 on 2026-05-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0014_alter_learnerprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('CCS', 'Ccs'), ('CBA', 'Cba'), ('COE', 'Coe'), ('CASED', 'Cased'), ('CON', 'Con'), ('COA', 'Coa'), ('Graduate_School', 'Graduate School')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='netlablog',
            name='department',
            field=models.CharField(blank=True, choices=[('CCS', 'Ccs'), ('CBA', 'Cba'), ('COE', 'Coe'), ('CASED', 'Cased'), ('CON', 'Con'), ('COA', 'Coa'), ('Graduate_School', 'Graduate School')], max_length=20, null=True),
        ),
    ]
