# Generated by Django 6.0.5 on 2026-06-05 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0015_alter_learnerprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='full_name',
            field=models.CharField(help_text='The official Full Name of the Learner.', max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z \\.\\-ñÑ]*$', 'Only letters and spaces are allowed.')]),
        ),
        migrations.AlterField(
            model_name='netlablog',
            name='name',
            field=models.CharField(help_text='Full name of the user.', max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z \\.\\-ñÑ]*$', 'Only letters and spaces are allowed.')]),
        ),
        migrations.AlterField(
            model_name='netlablog',
            name='purpose',
            field=models.CharField(blank=True, help_text='The purpose of the visit (e.g., Internet, Print).', max_length=150, null=True),
        ),
    ]
